---
parser: "@typescript-eslint/parser"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:import/recommended
  - plugin:import/typescript
plugins:
  - "@typescript-eslint"
  - prettier
  - import
parserOptions:
  ecmaVersion: 2020
  project:
    - tsconfig.json
  sourceType: module
overrides:
  - files:
      - "tests/**"
    plugins:
      - jest
      - jest-formatting
    extends:
      - plugin:jest/all
      - plugin:jest-formatting/recommended
settings:
  import/parsers:
    "@typescript-eslint/parser":
      - .ts
      - .tsx
  import/resolver:
    typescript: true
    node: true
rules:
  eol-last:
    - error
    - always
  "@typescript-eslint/no-unused-vars":
    - warn
    - varsIgnorePattern: "^_"
      argsIgnorePattern: "^_"
      caughtErrorsIgnorePattern: "^_"
      destructuredArrayIgnorePattern: "^_"
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
        - type
        - unknown
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
        # orderImportKind: asc
  jest/prefer-expect-assertions:
    - error
    - onlyFunctionsWithAsyncKeyword: true
      onlyFunctionsWithExpectInLoop: true
      onlyFunctionsWithExpectInCallback: true
