name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - run: npm ci
      # NOTE: Because npm `prepare` script is already ran in `npm ci`, we don't need a typecheck step.
      # - run: npm run typecheck
      - run: npm run lint
      - run: npm test
